# Logger configurations.
localmode: true

SLACK_BOT_TOKEN: xoxb-
SLACK_SIGNING_SECRET: xapp-1-
SLACK_CHANNEL_URL: https://hooks.slack.com/services/
PROXY_TO_API_ENDPOINT: https://domain/slack/clock-time
PROXY_TO_API_TOKEN: ""

logger:
  Path:                  "/tmp"
  Level:                 "all"
  file:                  "slackbot-{Y-m-d}.log"         # 日志文件格式。默认为"{Y-m-d}.log"
  Stdout:                false
  RotateSize:            "20M"
  RotateBackupLimit:     2
  RotateBackupExpire:    "7d"
  RotateBackupCompress:  9
